### ISSUE TITLE
发布回复不能立即显示

### ISSUE THREAD

**Issue by XiaoHuanwise** [twtstudio/WePeiYang-Flutter#5]
**请描述您的Bug | Describe the bug**
一个对于发生的Bug的清晰描述

对于一个帖子进行回复并成功之后必须要重新刷新回复楼层才能看到自己回复的信息。

**复现步骤 | To Reproduce**
复现步骤

1. 点开一个帖子
2. 输入回复内容并发布
3. 下拉刷新回复

4. Scroll down to '....'
5. See error

**预期行为 | Expected behavior**
对于本来应该发生的行为的清晰描述

楼层创建成功后自动刷新楼层或直接添加一个“假”的新楼层。

**截图 | Screenshots**
如果方便，请提供具体截图

**设备信息 | Smartphone (please complete the following information):**
或长按版本号提供调试页面截图

应该是普遍存在的程序逻辑问题

**更多信息 | Additional context**
如果您还想提供一些其它信息，请放在这里

**Comment by steven12138** [comment]
正在修了
