### ISSUE TITLE
无法长按复制楼主发帖内容

### ISSUE THREAD

**Issue by XiaoHuanwise** [twtstudio/WePeiYang-Flutter#6]
**请描述您的Bug | Describe the bug**
一个对于发生的Bug的清晰描述

可以长按复制帖子的回复楼层的内容，但是无法长按复制帖子本身的内容。

**复现步骤 | To Reproduce**
复现步骤
1. 打开一个帖子
2. 长按帖子内容

3. Click on '....'
4. Scroll down to '....'
5. See error

**预期行为 | Expected behavior**
对于本来应该发生的行为的清晰描述

长按帖子内容可以像长按帖子回复楼层一样复制内容。

**截图 | Screenshots**
如果方便，请提供具体截图

**设备信息 | Smartphone (please complete the following information):**
 - Device: [Redmi Note 13 Pro]
 - OS: [Xiaomi HyperOS 1.0.1.0.UNRCNXM]
或长按版本号提供调试页面截图

**更多信息 | Additional context**
如果您还想提供一些其它信息，请放在这里

**Comment by steven12138** [comment]
收到 看看
