### ISSUE TITLE
消息中心一键清除点赞后，被点赞内容被删除

### ISSUE THREAD

**Issue by ruci1001** [twtstudio/WePeiYang-Flutter#7]
**请描述您的Bug | Describe the bug**
一个对于发生的Bug的清晰描述

**复现步骤 | To Reproduce**
复现步骤
1. 在有点赞通知的情况下点击消息中心
2. 点击右上角一键已读
3. 被点赞的通知全部消失

**预期行为 | Expected behavior**
对于本来应该发生的行为的清晰描述

点击一键清除后，原有点赞、湖底通知的内容应当保留，小红点应当消失
**截图 | Screenshots**
如果方便，请提供具体截图

**设备信息 | Smartphone (please complete the following information):**
或长按版本号提供调试页面截图

**更多信息 | Additional context**
如果您还想提供一些其它信息，请放在这里

**Comment by steven12138** [comment]
这个东西算一个bug吗（不是feature吗
